server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/598140795qqcom/sprincloud-config.git #填写你自己的github路径
          #填写你自己的github路径
          search-paths:
            - springcloud-config
          skip-ssl-validation: true
          username: 598140795@qq.com
          password: zpZLzjhi132218
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'